### ISSUE TITLE
IDs for modules should be unique on define?

### ISSUE THREAD

**Issue by nanodocumet** [alexyoung/turing.js#1]
From turing.touch, it says `turing.dom` should that be `turing.touch`?

https://github.com/alexyoung/turing.js/blob/master/turing.touch.js#L30

From turing.plugins, it says `turing.dom` shouled that be `turing.plugins`?

https://github.com/alexyoung/turing.js/blob/master/turing.plugins.js#L26

Thanks for the great articles!

**Comment by alexyoung** [comment]
Yes, thanks!

**Comment by nanodocumet** [comment]
Great learning experience! Thanks for the efforts!
